remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: AIRES Technical Research Applications Development
description: A showcase of our development and proof-of-concept applications and research 

show_downloads: false